### ISSUE TITLE
needs rftools base 1.15-1

### ISSUE THREAD

**Issue by smaynard** [Terrails/XNetGasses#1]
Hi 
        Trying to to use the mod and it says I need rftoolsbase-1.15-1 but I have rftoolsbase-1.15-1.0.0-alpha, is that not sufficient?

**Comment by Terrails** [comment]
To be honest, you shouldn't be using such an old version. The XNet version I've made this mod with is 2.1.2-beta which requires rftools-base 1.0.9 or above. So it's not sufficient.

**Comment by smaynard** [comment]
Ok, trying to run the later versions of McjtyLib & RFTools is causing the game to crash on loading, will follow that up.
