### ISSUE TITLE
Configs Not changing

### ISSUE THREAD

**Issue by Viakanr** [Terrails/XNetGasses#12]
I have changed the transfer rate of normal connecters to 100,000 and advanced connecters to 50,000,000 and the change will not take place after restarting my server.

**Comment by Terrails** [comment]
Ah. I found the issue. I've moved the configs to serverconfig now and it should work as intended. You will be able to make it work using `world/serverconfig/xnetgases.toml`. `config/xnetgases.toml` will not be a valid config file anymore and can be deleted. I'll have an update on curseforge in a few minutes (or however long it takes to approve it)
