### ISSUE TITLE
Question about XNet

### ISSUE THREAD

**Issue by Dertiende** [Terrails/XNetGasses#13]
Since I didn't get a response to the email.

XNet was updated recently and i want to do same for this addition. Will you accept my changes? You can check out the XNet changes on github to see what I want to do.
I write this because I don't want to do work that won't be used.

**Comment by Terrails** [comment]
Ooh, I for sure thought you were talking about 1.20.4 and was confused by it as Mcjty was doing some work on XNet in the `1.20.4_neo` branch. Sorry for not replying due to that.

Yes, I would accept any changes for sure. I would have done the work myself anyways if it came down to it.
