### ISSUE TITLE
ATM 6 Xnet not working for gasses

### ISSUE THREAD

**Issue by coolmoo** [Terrails/XNetGasses#2]
Xnet doesnt seem to recognize slurries as a gas and it doesnt recognize slurries as a liquid either so slurries needs the gas api tag added

**Comment by Terrails** [comment]
I don't know which slurries you're referring to exactly, but all this mod does is access the gas container using the Mekanism API. All the other things are handled by Mekanism (or by another mod if the gas is not from Mekanism), so this mod doesn't add any "tags". Also, liquids aren't handled by this mod at all. That feature is built into XNet.

Did you make sure that the container that you're using has enabled output/input on the side you're extracting/inserting?

**Comment by coolmoo** [comment]
Yep tested everything every way possible and nothin worked with slurries and as far as i know slurries are considered gas as only the pressurized tubes can handle the gas but when i hook it up to xnet it says nope this isnt a gas

**Comment by Terrails** [comment]
Weird, gonna look into it. It might be that gasses that require pressurized tubes are special in some way.

**Comment by Terrails** [comment]
Just uploaded it to curseforge, might take a couple of minutes for it to get accepted.
