### ISSUE TITLE
Port to 1.21.1

### ISSUE THREAD

**Issue by Terrails** [Terrails/XNetGasses#21]

**Comment by jpeaglesandkatz** [comment]
Wondering if their has been any movement towards a 1.21.1 update?

**Comment by Terrails** [comment]
Yes, I am currently working on it, but do not have a whole lot of time available. I do hope to have a release by the end of this week.

**Comment by jpeaglesandkatz** [comment]
Thanks a lot, much appreciated

Verzonden met Proton Mail Android

-------- Oorspronkelijk bericht --------
Op 25-11-2024 11:21, schreef Filip :

**Comment by Terrails** [comment]
An initial release is up on CF and Modrinth. I have done some testing but there may be some issues that I have missed.

**Comment by jpeaglesandkatz** [comment]
Sorry for not responding earlier.. RL stuff :( Thanks a lot for your efforts.. I will give it a go as soon as I can...
