### ISSUE TITLE
No gas extracted from Quantum Entangloporter when using 'Min'

### ISSUE THREAD

**Issue by cornytrace** [Terrails/XNetGasses#5]
I have xnet set up to transfer Fissile Fuel from a Quantum Entangloporter into a reactor. This works, but I want to keep 64000mB in the QE, but when i enter any value into the 'Min' field, it stops working. It does not matter if the value is above or below the level in the QE, as soon as any number is entered into the field gas stops being transferred. The same problem appears for the 'Max' field when inserting. I am using the All the Mods 6 1.5.2 modpack, minecraft 1.16, mod version 2.2.3
Thanks for this incredibly useful mod, and I hope you can help me with my problem.

**Comment by Terrails** [comment]
Ah, thank you. I seem to have missed this while rewriting some behaviour.
