### ISSUE TITLE
Gas is not pulled in priority order

### ISSUE THREAD

**Issue by cornytrace** [Terrails/XNetGasses#6]
I have two machines outputting the same gas set to extract mode, one of priority 1 and the other of priority 0. The channel is in priority mode.
What I expect: the machine with priority 1 is completely drained before machine prio 0 begins to be drained.
What I observe: When a large amount of fluid fits in the inserted machine, both extract machines are being drained equally, at the same time. When only one/a few mB fit into the inserted machine, the only extract machine being drained is the priority 0 machine.
This is with XNetGases 2.2.4, XNet 1.16-3.0.11, minecraft 1.16.5
By the way, your 2.2.4 version solved my previous issue, thanks for the quick response!

**Comment by Terrails** [comment]
This issue seems to exist within XNet itself too, as I tested this with fluids and the same happened. I basically copied the logic for fluid from xnet for gases and slurries, so that's the reason its happening here too, but I will try to look into how I would go about this.

**Comment by cornytrace** [comment]
I see. Perhaps I should make an issue on the XNet github too, then.

**Comment by Terrails** [comment]
I have implemented this feature in dev, but I've just noticed that the same is happening with machines that have priority specified on insert. Going to do that and there will hopefully be a working release available soon.

**Comment by Terrails** [comment]
It's up on CurseForge now, please do tell me if it is working as intended :D !

**Comment by cornytrace** [comment]
It seems to work excellently! Thank you once again for the quick and effective help!
My fission reactor is now properly fueled first by the reprocessed fuel, and only then by newly made fuel.
